"use client";

/**
 * 3D Lab — Experiment 3: Load a Python-generated GLB.
 *
 * Proves the full pipeline: Python (TripoSR/trimesh) → .glb file → Three.js
 * The test_bot.glb was generated by tools/3d-gen/generate_3d.py
 */

import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

export default function GlbLabPage() {
    const containerRef = useRef<HTMLDivElement>(null);
    const [status, setStatus] = useState("Loading GLB...");
    const [modelInfo, setModelInfo] = useState<{
        vertices: number;
        faces: number;
        materials: number;
        fileSize: string;
    } | null>(null);

    useEffect(() => {
        if (!containerRef.current) return;

        const container = containerRef.current;
        const width = container.clientWidth;
        const height = container.clientHeight;

        // ── Scene ────────────────────────────────
        const scene = new THREE.Scene();
        scene.background = new THREE.Color("#1a1a2e");
        scene.fog = new THREE.Fog("#1a1a2e", 8, 25);

        // ── Camera ───────────────────────────────
        const camera = new THREE.PerspectiveCamera(50, width / height, 0.1, 100);
        camera.position.set(2, 2, 2);

        // ── Renderer ─────────────────────────────
        const renderer = new THREE.WebGLRenderer({ antialias: true });
        renderer.setSize(width, height);
        renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
        renderer.shadowMap.enabled = true;
        renderer.shadowMap.type = THREE.PCFSoftShadowMap;
        renderer.toneMapping = THREE.ACESFilmicToneMapping;
        renderer.toneMappingExposure = 1.2;
        container.appendChild(renderer.domElement);

        // ── Controls ─────────────────────────────
        const controls = new OrbitControls(camera, renderer.domElement);
        controls.enableDamping = true;
        controls.dampingFactor = 0.08;
        controls.target.set(0, 0.2, 0);

        // ── Lighting ─────────────────────────────
        scene.add(new THREE.AmbientLight("#404060", 1.0));
        const keyLight = new THREE.DirectionalLight("#ffeedd", 2.0);
        keyLight.position.set(3, 5, 3);
        keyLight.castShadow = true;
        keyLight.shadow.mapSize.set(1024, 1024);
        scene.add(keyLight);
        scene.add(new THREE.DirectionalLight("#8888ff", 0.8).translateX(-3).translateY(3).translateZ(-2));
        scene.add(new THREE.PointLight("#ff4400", 0.5, 8).translateX(-1).translateY(1).translateZ(2));

        // ── Floor ────────────────────────────────
        const floor = new THREE.Mesh(
            new THREE.PlaneGeometry(20, 20),
            new THREE.MeshStandardMaterial({ color: "#2a2a3a", metalness: 0.2, roughness: 0.8 })
        );
        floor.rotation.x = -Math.PI / 2;
        floor.receiveShadow = true;
        scene.add(floor);
        scene.add(new THREE.GridHelper(8, 16, "#333355", "#222244"));

        // ── Load the GLB ─────────────────────────
        const loader = new GLTFLoader();
        loader.load(
            "/parts/test_bot.glb",
            (gltf) => {
                const model = gltf.scene;
                model.castShadow = true;
                model.traverse((child) => {
                    if (child instanceof THREE.Mesh) {
                        child.castShadow = true;
                        child.receiveShadow = true;
                    }
                });

                // Center and scale the model
                const box = new THREE.Box3().setFromObject(model);
                const center = box.getCenter(new THREE.Vector3());
                const size = box.getSize(new THREE.Vector3());
                const maxDim = Math.max(size.x, size.y, size.z);
                const scale = 2 / maxDim; // Normalize to ~2 units
                model.scale.setScalar(scale);
                model.position.sub(center.multiplyScalar(scale));
                model.position.y += size.y * scale / 2;

                scene.add(model);

                // Count stats
                let verts = 0;
                let faces = 0;
                let mats = 0;
                const matSet = new Set<string>();
                model.traverse((child) => {
                    if (child instanceof THREE.Mesh) {
                        const geo = child.geometry as THREE.BufferGeometry;
                        verts += geo.attributes.position.count;
                        faces += (geo.index ? geo.index.count : geo.attributes.position.count) / 3;
                        if (child.material) {
                            const mat = child.material as THREE.Material;
                            matSet.add(mat.uuid);
                        }
                    }
                });
                mats = matSet.size;

                queueMicrotask(() => {
                    setStatus("✅ GLB loaded from Python pipeline!");
                    setModelInfo({
                        vertices: verts,
                        faces: Math.round(faces),
                        materials: mats,
                        fileSize: "13.5 KB",
                    });
                });
            },
            (progress) => {
                if (progress.total > 0) {
                    const pct = Math.round((progress.loaded / progress.total) * 100);
                    queueMicrotask(() => setStatus(`Loading: ${pct}%`));
                }
            },
            (error) => {
                console.error("GLB load error:", error);
                queueMicrotask(() => setStatus(`❌ Failed to load GLB: ${error}`));
            }
        );

        // ── Animation ────────────────────────────
        const clock = new THREE.Clock();
        let animId: number;

        function animate() {
            animId = requestAnimationFrame(animate);
            controls.update();
            renderer.render(scene, camera);
        }
        animate();

        // ── Resize ───────────────────────────────
        function onResize() {
            const w = container.clientWidth;
            const h = container.clientHeight;
            camera.aspect = w / h;
            camera.updateProjectionMatrix();
            renderer.setSize(w, h);
        }
        window.addEventListener("resize", onResize);

        return () => {
            window.removeEventListener("resize", onResize);
            cancelAnimationFrame(animId);
            controls.dispose();
            renderer.dispose();
            if (container.contains(renderer.domElement)) {
                container.removeChild(renderer.domElement);
            }
        };
    }, []);

    return (
        <div style={{ width: "100vw", height: "100vh", position: "relative", background: "#1a1a2e" }}>
            <div
                style={{
                    position: "absolute",
                    top: 16,
                    left: 16,
                    zIndex: 10,
                    color: "#ffffff",
                    fontFamily: "monospace",
                    fontSize: 13,
                    background: "rgba(0,0,0,0.7)",
                    padding: "12px 16px",
                    borderRadius: 8,
                    maxWidth: 420,
                }}
            >
                <div style={{ fontWeight: "bold", color: "#00ff88", fontSize: 15, marginBottom: 8 }}>
                    🔬 3D Lab — Experiment 3: GLB from Python
                </div>
                <div style={{ marginBottom: 8 }}>{status}</div>

                {modelInfo && (
                    <div style={{ fontSize: 12, color: "#aaa" }}>
                        <div>📐 Vertices: <span style={{ color: "#ffaa00" }}>{modelInfo.vertices}</span></div>
                        <div>🔺 Faces: <span style={{ color: "#ffaa00" }}>{modelInfo.faces}</span></div>
                        <div>🎨 Materials: <span style={{ color: "#ffaa00" }}>{modelInfo.materials}</span></div>
                        <div>📦 File: <span style={{ color: "#ffaa00" }}>{modelInfo.fileSize}</span></div>
                    </div>
                )}

                <div style={{ marginTop: 8, fontSize: 11, color: "#666" }}>
                    Pipeline: generate_3d.py (trimesh) → test_bot.glb → Three.js GLTFLoader
                </div>
            </div>

            <div
                style={{
                    position: "absolute",
                    bottom: 16,
                    left: 16,
                    zIndex: 10,
                    color: "#aaa",
                    fontFamily: "monospace",
                    fontSize: 12,
                    background: "rgba(0,0,0,0.5)",
                    padding: "8px 12px",
                    borderRadius: 6,
                }}
            >
                🖱️ Drag to orbit | Source: public/parts/test_bot.glb (generated by Python)
            </div>

            <div ref={containerRef} style={{ width: "100%", height: "100%" }} />
        </div>
    );
}
